# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class chauffage_et_climatisation_tour_aerorefrigerante_tar_var_0(BaseModel):
    type_de_control : Optional[Literal['Nettoyage annuel', 'Contrôle périodique', 'Mesure des polluants rejetés', 'Analyse des Legionella pneumophila']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service de la tour aéro-réfrigérante, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut de le tour aéro-réfrigérante, si présent.")
    volume_d_eau_m3_var : Optional[float] = Field(description="Le volume d'eau de la tour aéro-réfrigérante en m3, si présent.")
    debit_d_eau_m3_h_var : Optional[float] = Field(description="Le débit d'eau de la tour aéro-réfrigérante en m3/h, si présent.")
    temperature_nominale_entree_c_var : Optional[float] = Field(description="La température nominale d'entrée de la tour aéro-réfrigérante en °C, si présent.")


class chauffage_et_climatisation_tour_aerorefrigerante_tar_var_1(BaseModel):
    temperature_nominale_sortie_c_var : Optional[float] = Field(description="La température nominale de sortie de la tour aéro-réfrigérante en °C, si présent.")
    presence_de_protection_sur_les_reseaux_d_appoints_var : Optional[bool] = Field(description="La présence de protection sur les réseaux d'appoints, si présent.")
    domaine_d_utilisation : Optional[str] = Field(description="Le domaine d'utilisation de la tour aéro-réfrigérante, si présent.")
    puissance_totale_evacuee_du_site_kw_var : Optional[float] = Field(description="La puissance totale évacuée du site en kW, si présent.")
    presence_de_separateur_de_gouttelettes_var : Optional[bool] = Field(description="La présence de séparateur de gouttelettes, si présent.")
    nombre_de_tours_en_parallele : Optional[int] = Field(description="Le nombre de tours en parallèle, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant de la tour aéro-réfrigérante, si présent.")


class chauffage_et_climatisation_tour_aerorefrigerante_tar_var_2(BaseModel):
    l_installation_est_elle_certifiee_conforme_par_la_norme_internationale_iso_14001_var : Optional[bool] = Field(description="L'installation est-elle certifiée conforme par la norme internationale ISO 14001, si présent.")
    sous_quel_regime_de_la_rubrique_2921_est_classee_l_installation_var : Optional[Literal['Déclaration (DC)', 'Enregistrement (E)', 'Non classée dans rubrique 2921', '']] = Field(description="Sous quel régime de la rubrique 2921 est classée l'installation, si présent.")
    etes_vous_dans_l_impossibilite_technique_ou_economique_de_realiser_l_arret_annuel_de_l_installation_nettoyage_et_desinfection_var : Optional[bool] = Field(description="Êtes-vous dans l'impossibilité technique ou économique de réaliser l'arrêt annuel de l'installation (nettoyage et désinfection), si présent.")
    puissance_de_la_tar_en_kw_var : Optional[float] = Field(description="La puissance de la tour aéro-réfrigérante en kW, si présent.")


class chauffage_et_climatisation_tour_aerorefrigerante_tar_var_3(BaseModel):
    quel_type_de_protection_var : Optional[str] = Field(description="Le type de protection sur les réseaux d'appoints, si présent.")
    type_de_corps_d_echange : Optional[str] = Field(description="Le type de corps d'échange de la tour aéro-réfrigérante, si présent.")
    type_de_separateur : Optional[str] = Field(description="Le type de séparateur de gouttelettes, si présent.")
    type_d_eau_d_appoint : Optional[str] = Field(description="Le type d'eau d'appoint, si présent.")
    type_de_fonctionnement : Optional[Literal['Continu', 'Intermittent', '']] = Field(description="Le type de fonctionnement de la tour aéro-réfrigérante, si présent.")
    type_de_tour : Optional[Literal['Ouverte', 'Fermée', 'Hybride', '']] = Field(description="Le type de tour aéro-réfrigérante, si présent.")
