# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class chauffage_et_climatisation_climatisations_pac_et_fluides_frigorigenes_0(BaseModel):
    type_de_control : Optional[Literal['Entretien', 'Inspection périodique', 'Vérification des systèmes permanents de détection de fuite', "Contrôle d'étanchéité"]] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service de la climatisation, si présent.")
    mobilite : Optional[Literal['Fixe', 'Mobile']] = Field(description="La mobilité de l'équipement de la climatisation, si présent.")
    date_de_fabrication : Optional[str] = Field(description="La date de fabrication (peut être appelé plaque) de la climatisation, si présent.")
    quantite_de_fluide_frigorigene_tonnes_equivalent_co2_var : Optional[float] = Field(description="La quantité de fluide frigorigène en tonnes équivalent CO2, si présent.")
    gwp : Optional[float] = Field(description=".")
    presence_d_un_systeme_permanent_de_detection_de_fuites : Optional[bool] = Field(description="La présence d'un système permanent de détection de fuites, si présent.")
    quantite_de_fluide_frigorigene_kg_var : Optional[float] = Field(description="La quantité de fluide frigorigène en kilogrammes, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant de la climatisation, si présent.")
    le_systeme_est_couvert_par_une_certification_iso_50001_var : Optional[bool] = Field(description="Le système est-il couvert par une certification ISO 50001, si présent.")
    nature_du_gaz : Optional[Literal['Hydrochlorofluorocarbures (HCFC)', 'Hydrofluorocarbures (HFC)', 'Perfluorocarbones (PFC)', 'Autre', '']] = Field(description="La nature du gaz, si présent.")
    charge_en_hcfc_kg_var : Optional[float] = Field(description="La charge en HCFC en kilogrammes, si présent.")
    charge_en_hfc_ou_pfc_tonnes_equivalent_co2_var : Optional[float] = Field(description="La charge en HFC ou PFC en tonnes équivalent CO2, si présent.")
    seuil_de_detection : Optional[Literal["50g/h ou 10% de la charge totale du fluide contenu dans l'équipement", 'Seuil supérieur', '']] = Field(description="Le seuil de détection, si présent.")
    nom_du_gaz : Optional[str] = Field(description="Le nom du gaz, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut de la climatisation, si présent.")
    avez_vous_un_contrat_de_performance_energetique_sur_cette_installation_var : Optional[bool] = Field(description="Avez-vous un contrat de performance énergétique sur cette installation, si présent.")
    puissance_nominale_kw_var : Optional[float] = Field(description="La puissance nominale de la climatisation en kilowatts, si présent.")
    le_batiment_ou_la_zone_de_production_contient_il_plusieurs_systemes_thermodynamiques_var : Optional[bool] = Field(description="Le bâtiment ou la zone de production contient-il plusieurs systèmes thermodynamiques, si présent.")
    somme_des_puissances_nominales_des_systemes_thermodynamiques_du_batiment_en_kw_var : Optional[float] = Field(description="La somme des puissances nominales des systèmes thermodynamiques du bâtiment en kilowatts, si présent.")
    modele : Optional[str] = Field(description="Le modèle (ou type) de la climatisation, si présent.")
    type_de_methode_de_detection_de_fuites : Optional[Literal['Directe', 'Indirecte', '']] = Field(description="Le type de méthode de détection de fuites, si présent.")
    type_element : Optional[Literal['Équipement de réfrigération', 'Équipement de climatisation', 'Pompe à chaleur', 'Unité de réfrigération des camions et remorques frigorifiques', 'Cycle organique de Rankine', '']] = Field(description="Le type d'élément de la climatisation, si présent.")
    autre_type_de_gaz : Optional[str] = Field(description=".")
