# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class echelles_et_echafaudages_echelles_0(BaseModel):
    type_de_control : Optional[Literal['Vérification périodique']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service de l'échelle, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant de l'échelle, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut de l'echelle, si présent.")
    nombre_de_marche : Optional[int] = Field(description="Le nombre de marches de l'échelle, si présent.")
    hauteur : Optional[float] = Field(description="La hauteur de l'échelle, si présent.")
    type_element : Optional[Literal['Echelle', 'Echelle à crinoline', 'Escabeau', 'Gazelle', 'Marchepied', "Pied d'éléphant", 'PIR', 'PIRL', 'Tabouret', 'Échelle avec garde-corps', 'Plateforme saut de loup', 'Autre', '']] = Field(description="Le type d'élément de l'échelle, si présent.")
