# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class echelles_et_echafaudages_echafaudage_0(BaseModel):
    type_de_control : Optional[Literal['Vérification périodique']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service de l'échafaudage, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant de l'échafaudage, si présent.")
    nombre : Optional[int] = Field(description="Le nombre d'échafaudages, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut de l'échaufaudage, si présent.")
    l_echafaudage_est_il_dans_le_cas_d_une_utilisation_inferieure_a_3_mois_var : Optional[bool] = Field(description="L'échafaudage est-il dans le cas d'une utilisation inférieure à 3 mois, si présent.")
