# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class equipements_de_protection_individuelle_travail_en_hauteur_0(BaseModel):
    type_de_control : Optional[Literal['Vérification périodique']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_fabrication : Optional[str] = Field(description="La date de fabrication (peut être appelé plaque) de l'équipement de protection individuelle pour le travail en hauteur, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service de l'équipement de protection individuelle pour le travail en hauteur, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant de l'équipement de protection individuelle pour le travail en hauteur, si présent.")
    capacite_kg_var : Optional[int] = Field(description="La capacité de charge maximale de l'équipement de protection individuelle pour le travail en hauteur, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut de l'équipement de protection individuelle pour le travail en hauteur, si présent.")
    assigne_a : Optional[str] = Field(description="La personne à qui l'équipement de protection individuelle pour le travail en hauteur est assignée, si présent.")
    modele : Optional[str] = Field(description="Le modèle (ou type) de l'équipement de protection individuelle pour le travail en hauteur, si présent.")
    marquage_ce : Optional[bool] = Field(description="Le marquage CE est-il présent.")
    type_element : Optional[Literal['Longe', 'Sangle', 'Mousqueton', 'Harnais', 'Descendeur', 'Absorbeur', 'Poulie', 'Perche', 'Corde', 'Antichute', 'Bloqueur', 'Stop-chute', 'Porte-outils', 'Autre', '']] = Field(description="Le type d'élément de l'équipement de protection individuelle pour le travail en hauteur, si présent.")
