# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class equipements_de_protection_individuelle_materiel_d_urgence_0(BaseModel):
    type_de_control : Optional[Literal['Vérification périodique']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    mobilite : Optional[Literal['Fixe', 'Portatif']] = Field(description="La mobilité du matériel d'urgence, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service du matériel d'urgence, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut du matériel d'urgence, si présent.")
    nombre : Optional[int] = Field(description="Le nombre de matériel d'urgence, si présent.")
    modele : Optional[str] = Field(description="Le modèle (ou type) du matériel d'urgence, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant du matériel d'urgence, si présent.")
    taille : Optional[str] = Field(description="La taille du matériel d'urgence, si présent.")
    assigne_a : Optional[str] = Field(description="La personne à qui le matériel d'urgence est assigné, si présent.")
    type_de_defibrillateur : Optional[Literal['Automatique\u202f', 'Semi-automatique', '']] = Field(description="Le type de défibrillateur, si présent.")
    autre_type_d_installation : Optional[str] = Field(description=".")
    type_de_lavage_d_urgence : Optional[Literal['Douche de sécurité', 'Rince-œil', 'Combiné douche et rince-œil', '']] = Field(description="Le type de lavage d'urgence, si présent.")
    type_d_installation : Optional[Literal['Lavage d’urgence', 'Défibrillateur', 'Trousse de secours', 'Gilet de sauvetage', 'Autre', '']] = Field(description="Le type d'installation du matériel d'urgence, si présent.")
