# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class equipements_sous_pression_accessoire_sous_pression_0(BaseModel):
    type_de_control : Optional[Literal['IP arrêt', 'RP', 'Contrôle périodique']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service de l'accessoire sous pression, si présent.")
    date_de_fabrication : Optional[str] = Field(description="La date de fabrication (peut être appelé plaque) de l'accessoire sous pression, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant de l'accessoire sous pression, si présent.")
    regime_de_fabrication : Optional[Literal['2 avril 1926 (vapeur)', 'Janvier 1943 (gaz)', 'DESP 97/23/CE', 'DESP 2014/68/UE', '']] = Field(description="Le régime de fabrication de l'accessoire sous pression, si présent.")
    pid : Optional[str] = Field(description="Le PID de l'accessoire sous pression, si présent.")
    volume_en_l_var : Optional[float] = Field(description="Le volume en litres de l'accessoire sous pression, si présent.")
    pression_de_service_en_bar_var : Optional[float] = Field(description="La pression de service en bar de l'accessoire sous pression, si présent.")
    materiau : Optional[str] = Field(description="Le matériau de l'accessoire sous pression, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut de l'accessoire sous pression, si présent.")
    longueur_en_m_var : Optional[float] = Field(description="La longueur en mètres de l'accessoire sous pression, si présent.")
    pression_d_epreuve_en_bar_var : Optional[float] = Field(description="La pression d'épreuve en bar de l'accessoire sous pression, si présent.")
    type_d_accessoire_sous_pression : Optional[Literal['Flexible', 'Vanne', 'Réservoir', 'Ballon', 'Filtre', 'Autre', '']] = Field(description="Le type d'accessoire sous pression, si présent.")
    autre_type_d_accessoire : Optional[str] = Field(description=".")
