# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class equipements_de_protection_individuelle_stock_de_cartouche_pour_appareil_respiratoire_0(BaseModel):
    type_de_control : Optional[Literal['Vérification périodique']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service de la cartouche pour appareil respiratoire, si présent.")
    modele : Optional[str] = Field(description="Le modèle (ou type) de la cartouche pour appareil respiratoire, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant de la cartouche pour appareil respiratoire, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut de la cartouche pour appareil respiratoire, si présent.")
    assigne_a : Optional[str] = Field(description="La personne à qui la cartouche pour appareil respiratoire est assignée, si présent.")
