# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class exposition_des_travailleurs_eclairage_0(BaseModel):
    type_de_control : Optional[Literal['Vérification périodique']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_la_derniere_analyse : Optional[str] = Field(description=".")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description=".")
    zone_d_eclairement : Optional[Literal['Voies de circulation intérieure', 'Zones et voies de circulation extérieure', 'Escaliers et entrepôts', 'Locaux de travail, vestiaires et sanitaires', 'Locaux aveugles affectés à un travail permanent', 'Espaces extérieurs où sont effectués des travaux à caractère permanent', 'Autre', '']] = Field(description=".")
    valeur_d_eclairement_mesuree_en_lux_var : Optional[float] = Field(description=".")
    autre_type_de_zone : Optional[str] = Field(description=".")
