# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class exposition_des_travailleurs_risque_chimique_0(BaseModel):
    type_de_control : Optional[Literal['Evaluation des risques', "Mesurage de l'exposition", 'Contrôle technique', 'Vérification périodique']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_la_derniere_analyse : Optional[str] = Field(description=".")
    categorie_de_cmr : Optional[Literal['1A', '1B', '2', '']] = Field(description=".")
    presence_d_installation_de_production_et_de_distribution_d_air_respirable : Optional[bool] = Field(description=".")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description=".")
    nature_du_risque_evalue : Optional[Literal['Agents chimiques dangereux', 'Amiante', 'Silice', 'Agents CMR', 'Plomb', 'Autre', '']] = Field(description=".")


class exposition_des_travailleurs_risque_chimique_1(BaseModel):
    denomination_de_l_agent_chimique : Optional[str] = Field(description=".")
    reference_de_l_installation_d_air : Optional[str] = Field(description=".")
    presence_d_extracteurs_et_d_equipement_d_aspiration_des_poussieres : Optional[bool] = Field(description=".")
    reference_de_l_installation_d_extraction_aspiration : Optional[str] = Field(description=".")
    numero_ce : Optional[str] = Field(description=".")
    numero_cas : Optional[str] = Field(description=".")
    valeur_limite_d_exposition_professionnelle_en_mg_m3_var : Optional[float] = Field(description=".")
    valeur_limite_d_exposition_professionnelle_en_ppm_var : Optional[float] = Field(description=".")
    phrase_de_risque_mention_de_danger : Optional[str] = Field(description=".")


class exposition_des_travailleurs_risque_chimique_2(BaseModel):
    type_de_cmr : Optional[Literal['Cancérigène', 'Mutagène', 'Repro-toxique', '']] = Field(description=".")
    type_de_silice : Optional[str] = Field(description=".")
    type_d_amiante : Optional[str] = Field(description=".")
    autre_type_de_risque : Optional[str] = Field(description=".")
