# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class exposition_des_travailleurs_vibration_mecanique_0(BaseModel):
    type_de_control : Optional[Literal['Évaluation des niveaux de vibration']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_la_derniere_evaluation_des_vibrations_mecaniques : Optional[str] = Field(description=".")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description=".")
    poste_de_travail : Optional[str] = Field(description=".")
    lieu_de_la_mesure : Optional[str] = Field(description=".")
    equipement_utilise : Optional[str] = Field(description=".")
    exposition_quotidienne_en_m_s_var : Optional[float] = Field(description=".")
