# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class installations_electriques_eclairage_de_securite_0(BaseModel):
    type_de_control : Optional[Literal['Vérification périodique du fonctionnement', "Vérification d'autonomie"]] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service de l'installation électrique d'éclairage de sécurité, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut de l'installation électrique d'éclairage de sécurité, si présent.")
    modele : Optional[Literal['Permanent à fluorescence', 'Non permanent à fluorescence', 'À incandescence', 'À diodes électroluminescentes', '']] = Field(description="Le modèle (ou type) de l'installation électrique d'éclairage de sécurité, si présent.")
    nombre_de_dispositif_present_dans_l_installation : Optional[int] = Field(description="Le nombre de dispositif présent dans l'installation électrique d'éclairage de sécurité, si présent.")
    l_installation_est_elle_equipee_d_une_fonction_dbr_var : Optional[bool] = Field(description="L'installation est-elle équipée d'une fonction DBR, si présent.")
    l_installation_est_elle_equipee_d_un_sati_var : Optional[bool] = Field(description="L'installation est-elle équipée d'un SATI, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant de l'installation électrique d'éclairage de sécurité, si présent.")


class installations_electriques_eclairage_de_securite_1(BaseModel):
    type_d_eclairage : Optional[Literal['Evacuation', 'Anti-panique ou ambiance', 'Autre', '']] = Field(description="Le type d'éclairage de l'installation électrique d'éclairage de sécurité, si présent.")
    autre_type_d_installation : Optional[str] = Field(description=".")
    type_d_installation : Optional[Literal['BAES', 'LSC', 'Autre', '']] = Field(description="Le type d'installation de l'installation électrique d'éclairage de sécurité, si présent.")
