# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class installations_electriques_foudre_0(BaseModel):
    type_de_control : Optional[Literal['Vérification visuelle', 'Vérification complète']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service de l'installation électrique de foudre, si présent.")
    structure_du_batiment : Optional[str] = Field(description="La structure du bâtiment de l'installation électrique de foudre, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut de l'installation électrique de foudre, si présent.")
    toiture_du_batiment : Optional[str] = Field(description="La toiture du bâtiment de l'installation électrique de foudre, si présent.")
    parois_du_batiment : Optional[str] = Field(description="Les parois du bâtiment de l'installation électrique de foudre, si présent.")


class installations_electriques_foudre_1(BaseModel):
    uc_v_var : Optional[float] = Field(description=".")
    up_kv_var : Optional[float] = Field(description=".")
    in_ka_var : Optional[float] = Field(description=".")
    limp_ka_var : Optional[float] = Field(description=".")
    marque_reference : Optional[str] = Field(description="La marque de référence de l'installation électrique de foudre, si présent.")
    protection : Optional[str] = Field(description="La protection de l'installation électrique de foudre, si présent.")
    niveau_de_protection_defini_par_l_analyse_foudre_effets_indirects_var : Optional[Literal['I', 'II', 'III', 'IV', '']] = Field(description="Le niveau de protection défini par l'analyse de foudre des effets indirects de l'installation électrique de foudre, si présent.")


class installations_electriques_foudre_2(BaseModel):
    composition_de_l_installation_exterieure : Optional[Literal['Dispositif de capture', 'Dispositif de conducteurs de descente', 'Prise de terre', '']] = Field(description="La composition de l'installation extérieure de l'installation électrique de foudre, si présent.")
    isscr_ka_var : Optional[float] = Field(description=".")
    calibre : Optional[str] = Field(description="Le calibre de l'installation électrique de foudre, si présent.")
    nombre_de_dispositif_suivi : Optional[int] = Field(description="Le nombre de dispositif suivi de l'installation électrique de foudre, si présent.")
    niveau_de_protection_defini_par_l_analyse_foudre_effets_directs_var : Optional[Literal['I', 'II', 'III', 'IV', '']] = Field(description="Le niveau de protection défini par l'analyse de foudre des effets directs de l'installation électrique de foudre, si présent.")


class installations_electriques_foudre_3(BaseModel):
    type_du_parafoudre : Optional[Literal['I', 'II', 'III', '']] = Field(description="Le type du parafoudre de l'installation électrique de foudre, si présent.")
    type_de_systeme_de_protection_contre_la_foudre : Optional[Literal['Installation extérieure (IEPF)', 'Installation intérieure (IIPF)', '']] = Field(description="Le type de système de protection contre la foudre de l'installation électrique de foudre, si présent.")
    type_de_dispositif_de_conducteurs_descente : Optional[Literal['Descentes constituées de conducteurs foudres dédiées', 'Descentes constituées de la structure naturelle du bâtiment', '']] = Field(description="Le type de dispositif de conducteurs de descente de l'installation électrique de foudre, si présent.")
    type_de_dispositif_de_prise_de_terre : Optional[Literal['Composé de prise de terre locale', 'Composé de boucles de terre', '']] = Field(description="Le type de dispositif de prise de terre de l'installation électrique de foudre, si présent.")
    type_de_dispositif_de_capture : Optional[Literal['Cage maillée extérieure', 'Cage maillée naturelle', 'Pointe captrice', 'Fils tendus', ' Paratonnerre à dispositif d’amorçage (PDA)', 'Paratonnerre à tige simple (PTS)', '']] = Field(description="Le type de dispositif de capture de l'installation électrique de foudre, si présent.")
    type_de_suivi : Optional[Literal['Individuel', 'Ensemble', '']] = Field(description="Le type de suivi de l'installation électrique de foudre, si présent.")
