# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class levage_accessoire_0(BaseModel):
    type_de_control : Optional[Literal['Vérification générale périodique']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_fabrication : Optional[str] = Field(description="La date de fabrication (peut être appelé plaque) de l'accessoire de levage, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service de l'accessoire de levage, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant de l'accessoire de levage, si présent.")
    charge_maximale_d_utilisation_kg_var : Optional[int] = Field(description="La charge maximale d'utilisation de l'accessoire de levage, si présent.")
    etat_a_l_achat : Optional[Literal['Neuf', 'Occasion', '']] = Field(description="L'état à l'achat de l'accessoire de levage, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut de l'accessoir de levage, si présent.")
    modele : Optional[str] = Field(description="Le modèle (ou type) de l'accessoire de levage, si présent.")
    marquage_ce : Optional[bool] = Field(description="Le marquage CE est-il présent.")
    type_de_pince : Optional[Literal['À tôle', 'Lève-fût', 'Lève tuyaux', 'Lève blocs', 'Lève poutres', 'Autre', '']] = Field(description="Le type de pince de l'accessoire de levage, si présent.")
    type_d_anneau : Optional[Literal['Simple', 'Articulé', '']] = Field(description="Le type d'anneau de l'accessoire de levage, si présent.")
    type_de_palonnier : Optional[Literal['A crochets', 'A ventouses', '']] = Field(description="Le type de palonnier de l'accessoire de levage, si présent.")
    type_de_manille : Optional[Literal['Lyre', 'Droite', '']] = Field(description="Le type de manille de l'accessoire de levage, si présent.")
    type_de_crochet : Optional[Literal['Classique', 'En S', '']] = Field(description="Le type de crochet de l'accessoire de levage, si présent.")
    type_d_elingue : Optional[Literal['Câble', 'Chaîne', 'Textile', '']] = Field(description="Le type d'élingue de l'accessoire de levage, si présent.")
    type_element : Optional[Literal['Aimant', 'Anneau', 'Clé de levage', 'Crochet', 'Elingue', 'Griffe', 'Lève palette', 'Manille', 'Palonnier', 'Pince', 'Poulie de puits', 'Ventouse', 'Autre', '']] = Field(description="Le type d'élément de l'accessoire de levage, si présent.")
