# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class pmii_caniveaux_en_beton_0(BaseModel):
    type_de_control : Optional[Literal['Visite de surveillance', 'Visite de surveillance intermédiaire en service']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    categorie_de_l_ouvrage : Optional[Literal['Catégorie 1', 'Catégorie 2', '']] = Field(description="La catégorie de l'ouvrage, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service de l'ouvrage, si présent.")
    date_de_fabrication : Optional[str] = Field(description="La date de fabrication (peut être appelé plaque) de l'ouvrage, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant de l'ouvrage, si présent.")
    adresse_du_fabricant : Optional[str] = Field(description="L'adresse du fabricant de l'ouvrage, si présent.")
    lieu_de_fabrication : Optional[str] = Field(description="Le lieu de fabrication de l'ouvrage, si présent.")


class pmii_caniveaux_en_beton_1(BaseModel):
    hauteur_m_var : Optional[float] = Field(description="La hauteur en m de l'ouvrage, si présent.")
    longueur_m_var : Optional[float] = Field(description="La longueur en m de l'ouvrage, si présent.")
    l_ouvrage_appartient_il_a_une_unite_de_fabrication_vehiculant_des_produits_agressifs_pour_lui_var : Optional[bool] = Field(description="L'ouvrage appartient-il à une unité de fabrication véhiculant des produits agressifs pour lui, si présent.")
    l_unite_de_fabrication_comprend_il_un_equipement_pouvant_causer_un_risque_technologique_lors_de_la_defaillance_de_celui_ci_var : Optional[bool] = Field(description="L'unité de fabrication comprend-il un équipement pouvant causer un risque technologique lors de la défaillance de celui-ci, si présent.")
    periodicite_des_arrets_techniques_generaux_en_mois_var : Optional[int] = Field(description="La périodicité des arrêts techniques généraux en mois, si présent.")
    nature_de_l_etancheite : Optional[Literal['Béton', 'Membrane', 'Revêtement superficiel', 'Autre', '']] = Field(description="La nature de l'étanchéité de l'ouvrage, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut de l'ouvrage, si présent.")
