# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class pmii_bac_de_stockage_0(BaseModel):
    type_de_control : Optional[Literal['Visite de routine', 'Inspection hors exploitation', 'Inspection externe en exploitation']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_d_essai_hydraulique_initial : Optional[str] = Field(description="La date de l'essai hydraulique initial du bac de stockage, si présent.")
    date_de_fabrication : Optional[str] = Field(description="La date de fabrication (peut être appelé plaque) du bac de stockage, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service du bac de stockage, si présent.")
    phrase_de_risque_mention_de_danger : Optional[Literal['rien', '']] = Field(description="La phrase de risque mention de danger du bac de stockage, si présent.")
    calorifuge : Optional[bool] = Field(description="Le calorifuge du bac de stockage, si présent.")
    serpentin_de_rechauffage : Optional[bool] = Field(description="Le serpentin de réchauffage du bac de stockage, si présent.")


class pmii_bac_de_stockage_1(BaseModel):
    pression_de_service_bar_var : Optional[float] = Field(description="La pression de service en bar du bac de stockage, si présent.")
    adresse_du_fabricant : Optional[str] = Field(description="L'adresse du fabricant du bac de stockage, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant du bac de stockage, si présent.")
    lieu_de_fabrication : Optional[str] = Field(description="Le lieu de fabrication du bac de stockage, si présent.")
    hauteur_du_reservoir_m_var : Optional[float] = Field(description="La hauteur du réservoir en m du bac de stockage, si présent.")
    pression_de_calcul_bar_var : Optional[float] = Field(description="La pression de calcul en bar du bac de stockage, si présent.")
    volume_m3_var : Optional[float] = Field(description="Le volume en m3 du bac de stockage, si présent.")


class pmii_bac_de_stockage_2(BaseModel):
    pid : Optional[str] = Field(description="Le PID du bac de stockage, si présent.")
    temperature_de_calcul_c_var : Optional[float] = Field(description="La température de calcul en °C du bac de stockage, si présent.")
    temperature_de_service_c_var : Optional[float] = Field(description="La température de service en °C du bac de stockage, si présent.")
    produit_stocke : Optional[str] = Field(description="Le produit stocké dans le bac de stockage, si présent.")
    le_liquide_est_il_inflammable_var : Optional[bool] = Field(description="Le liquide est-il imflammable, si present.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut du bac de stockage, si présent.")


class pmii_bac_de_stockage_3(BaseModel):
    quelle_est_la_periodicite_de_la_nouvelle_inspection_hors_exploitation_detaillee_ihed_var : Optional[int] = Field(description="Quelle est la périodicité de la nouvelle inspection hors exploitation détaillée IHED, si présent.")
    les_resultats_des_inspections_recentes_permettent_ils_un_report_de_l_ihed_du_reservoir_var : Optional[bool] = Field(description="Les résultats des inspections récentes permettent-ils un report de l'IHED du réservoir, si présent.")
    est_il_exploite_dans_une_installation_soumise_a_une_des_rubriques_autorisees_par_l_am_du_03_10_2010_var : Optional[bool] = Field(description="Est-il exploité dans une installation soumise à une des rubriques autorisées par l'AM du 03/10/2010, si présent.")
    diametre_du_reservoir_m_var : Optional[str] = Field(description="Le diamètre du réservoir en m du bac de stockage, si présent.")
    materiau : Optional[Literal['Acier carbone', 'Acier inoxydable', 'Matériau composite', 'Métallique', 'Non métallique', 'Acier ignifugé', 'Fonte', 'Alliage Aluminium', 'Cuivre', 'Alliage cuivre', 'Nickel', 'Alliage de nickel', 'Nickel chrome', 'Titane', 'Alliage de titane', 'Graphite', 'Céramique', 'Polyester', 'Acier non allié', 'Aluminium non allié', 'Acier carbone manganèse', 'Acier faiblement allié', 'Acier allié', 'Acier inoxydable ferritique', 'Acier inoxydable austéno-ferritique', 'Acier inoxydable martensitique', 'Acier inoxydable austénitique', 'Matériaux ferreux\xa0', 'Matériaux non ferreux', '']] = Field(description="Le matériau du bac de stockage, si présent.")
    phase_du_fluide : Optional[Literal['Gaz', 'Vapeur ou eau surchauffée', 'Liquide dont la tension de vapeur, à TS, est inférieure à 0,5 bar à la pression atmosphérique normale (1,013 bar)', '']] = Field(description="La phase du fluide du bac de stockage, si présent.")
