# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class pmii_cuvette_de_retention_0(BaseModel):
    type_de_control : Optional[Literal['Visite de surveillance']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    categorie_de_l_ouvrage : Optional[Literal['Catégorie 1', 'Catégorie 2', '']] = Field(description="La catégorie de l'ouvrage, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service de la cuvette de rétention, si présent.")
    date_de_fabrication : Optional[str] = Field(description="La date de fabrication (peut être appelé plaque) de la cuvette de rétention, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant de la cuvette de rétention, si présent.")
    adresse_du_fabricant : Optional[str] = Field(description="L'adresse du fabricant de la cuvette de rétention, si présent.")
    lieu_de_fabrication : Optional[str] = Field(description="Le lieu de fabrication de la cuvette de rétention, si présent.")
    hauteur_de_la_retention_m_var : Optional[float] = Field(description="La hauteur de la rétention en m de la cuvette de rétention, si présent.")
    nature_de_l_etancheite_verticale : Optional[str] = Field(description="La nature de l'étanchéité verticale de la cuvette de rétention, si présent.")
    nature_de_l_etancheite_horizontale : Optional[str] = Field(description="La nature de l'étanchéité horizontale de la cuvette de rétention, si présent.")
    classe_d_etat : Optional[Literal['Classe 1', 'Classe 2', 'Classe 2E', 'Classe 3', 'Classe 3P', '']] = Field(description="La classe d'état de la cuvette de rétention, si présent.")
    volume_de_reference_m3_var : Optional[float] = Field(description="Le volume de référence en m3 de la cuvette de rétention, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut de la cuvette de rétention, si présent.")
    reseaux_d_evacuation_de_surface : Optional[str] = Field(description="Les réseaux d'évacuation de surface de la cuvette de rétention, si présent.")
    est_elle_mise_en_place_pour_prevenir_les_accidents_et_les_pollutions_accidentelles_susceptibles_d_etre_generes_par_les_equipements_contenus_var : Optional[bool] = Field(description="Est-elle mise en place pour prévenir les accidents et les pollutions accidentelles susceptibles d'être générés par les équipements contenus, si présent.")
