# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class pmii_reservoir_cryogenique_0(BaseModel):
    type_de_control : Optional[Literal['Inspection hors exploitation', 'Inspection externe en exploitation', 'Visite de routine']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_d_essai_hydraulique_initial : Optional[str] = Field(description="La date de l'essai hydraulique initial du réservoir cryogénique, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service du réservoir cryogénique, si présent.")
    date_de_fabrication : Optional[str] = Field(description="La date de fabrication (peut être appelé plaque) du réservoir cryogénique, si présent.")
    implante_sur_un_site_seveso_seuil_haut_ou_bas : Optional[bool] = Field(description="Est-il implanté sur un site SEVESO seuil haut ou bas, si présent.")
    calorifuge : Optional[bool] = Field(description="Le calorifuge du réservoir cryogénique, si présent.")
    hauteur_du_reservoir_m_var : Optional[float] = Field(description="La hauteur du réservoir en m, si présent.")


class pmii_reservoir_cryogenique_1(BaseModel):
    temperature_de_calcul_c_var : Optional[float] = Field(description="La température de calcul en °C du réservoir cryogénique, si présent.")
    adresse_du_fabricant : Optional[str] = Field(description="L'adresse du fabricant du réservoir cryogénique, si présent.")
    lieu_de_fabrication : Optional[str] = Field(description="Le lieu de fabrication du réservoir cryogénique, si présent.")
    pression_de_service_bar_var : Optional[float] = Field(description="La pression de service en bar du réservoir cryogénique, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant du réservoir cryogénique, si présent.")
    pid : Optional[str] = Field(description="Le PID du réservoir cryogénique, si présent.")
    volume_m3_var : Optional[float] = Field(description="Le volume en m3 du réservoir cryogénique, si présent.")


class pmii_reservoir_cryogenique_2(BaseModel):
    phase_du_fluide : Optional[Literal['Gaz', 'Vapeur ou eau surchauffée', 'Liquide dont la pression de vapeur à TS, est inférieure ou égale de 0,5 bar à la pression atmosphérique normale (1,013 bar)', '']] = Field(description="La phase du fluide du réservoir cryogénique, si présent.")
    pression_de_calcul_bar_var : Optional[float] = Field(description="La pression de calcul en bar du réservoir cryogénique, si présent.")
    temperature_de_service_c_var : Optional[float] = Field(description="La température de service en °C du réservoir cryogénique, si présent.")
    produit_stocke : Optional[str] = Field(description="Le produit stocké dans le réservoir cryogénique, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut du réservoir cryogénique, si présent.")
    diametre_du_reservoir_m_var : Optional[str] = Field(description="Le diamètre du réservoir en m, si présent.")
    phase_du_gaz : Optional[Literal['Gaz', 'Gaz liquéfié', 'Gaz dissous sous pression', 'Liquide dont la pression de vapeur, à TS, est supérieur à 0,5 bar à la pression atmosphérique normale (1,013bar)', '']] = Field(description="La phase du gaz du réservoir cryogénique, si présent.")
    materiau : Optional[Literal['Acier carbone', 'Acier inoxydable', 'Matériau composite', 'Métallique', 'Non métallique', 'Acier ignifugé', 'Fonte', 'Alliage Aluminium', 'Cuivre', 'Alliage cuivre', 'Nickel', 'Alliage de nickel', 'Nickel chrome', 'Titane', 'Alliage de titane', 'Graphite', 'Céramique', 'Polyester', 'Acier non allié', 'Aluminium non allié', 'Acier carbone manganèse', 'Acier faiblement allié', 'Acier allié', 'Acier inoxydable ferritique', 'Acier inoxydable austéno-ferritique', 'Acier inoxydable martensitique', 'Acier inoxydable austénitique', 'Matériaux ferreux\xa0', 'Matériaux non ferreux', '']] = Field(description="Le matériau du réservoir cryogénique, si présent.")


class pmii_reservoir_cryogenique_3(BaseModel):
    type_du_fluide : Optional[Literal['Toxique', 'Inflammable', 'Oxygène', "Gaz de distillation de l'air", 'Autre', '']] = Field(description="Le type du fluide du réservoir cryogénique, si présent.")
