# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class pmii_accessoire_de_securite_0(BaseModel):
    type_de_control : Optional[Literal['Vérification']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service de l'accessoire de sécurité, si présent.")
    pression_de_debut_d_ouverture_ou_pression_d_eclatement_en_bar_var : Optional[float] = Field(description="La pression de début d'ouverture ou pression d'éclatement en bar de l'accessoire de sécurité, si présent.")
    materiau : Optional[str] = Field(description="Le matériau de l'accessoire de sécurité, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant de l'accessoire de sécurité, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut de l'accessoire de sécurité, si présent.")
    pid : Optional[str] = Field(description="Le PID de l'accessoire de sécurité, si présent.")
    adequation_de_l_accessoire : Optional[bool] = Field(description="L'adéquation de l'accessoire de sécurité, si présent.")
    type_d_accessoire_de_securite : Optional[Literal['Disque de rupture', 'Soupape', 'DSDCS', 'CSPRS', 'SRMCR', 'Pompe', 'Pressostat de sécurité', 'Arrête-flamme', '']] = Field(description="Le type d'accessoire de sécurité, si présent.")
    type_d_arrete_flamme : Optional[Literal['Anti-déflagration en bout de ligne', 'Anti-déflagration en ligne', 'Anti-détonation', 'Mono ou bidirectionnel', '']] = Field(description="Le type d'arrête flamme de l'accessoire de sécurité, si présent.")
