# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class pmii_massif_de_reservoir_0(BaseModel):
    type_de_control : Optional[Literal['Visite de surveillance']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    categorie_de_l_ouvrage : Optional[Literal['Catégorie 1', 'Catégorie 2', '']] = Field(description="La catégorie de l'ouvrage, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service du massif de réservoir, si présent.")
    date_de_fabrication : Optional[str] = Field(description="La date de fabrication (peut être appelé plaque) du massif de réservoir, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant du massif de réservoir, si présent.")
    adresse_du_fabricant : Optional[str] = Field(description="L'adresse du fabricant du massif de réservoir, si présent.")
    lieu_de_fabrication : Optional[str] = Field(description="Le lieu de fabrication du massif de réservoir, si présent.")
    hauteur_du_massif_m_var : Optional[float] = Field(description="La hauteur du massif de réservoir en m, si présent.")
    classe_d_etat : Optional[Literal['Classe 1', 'Classe 2', 'Classe 2E', 'Classe 3', 'Classe 3P', '']] = Field(description="La classe d'état du massif de réservoir, si présent.")
    nature_du_massif : Optional[Literal['Assise simple en remblai compacté', 'Dalle en béton armé', 'Fondation sur pieux', 'Fondation sur inclusions rigides', '']] = Field(description="La nature du massif de réservoir, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut du massif de réservoir, si présent.")
