# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class portes_et_portails_portes_0(BaseModel):
    type_de_control : Optional[Literal['Vérification périodique']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service de la porte, si présent.")
    materiau : Optional[Literal['PVC', 'Bois', 'Aluminium', 'Acier', 'Inox', 'Fer', '']] = Field(description="Le matériau de la porte, si présent.")
    modele : Optional[str] = Field(description="Le modèle (ou type) de la porte (généralement le type), si présent.")
    mode_de_fonctionnement : Optional[Literal['Manuel', 'Automatique', 'Semi-automatique', '']] = Field(description="Le mode de fonctionnement de la porte, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant de la porte, si présent.")
    marquage_ce : Optional[bool] = Field(description="Le marquage CE est-il présent.")
    mode_d_ouverture_verticale : Optional[Literal['Sectionnel', 'Coulissant', 'Levant', '']] = Field(description="Le mode d'ouverture verticale de la porte, si présent.")
    mode_d_ouverture_horizontale : Optional[Literal['Battant', 'Coulissant', 'Sectionnel', 'Tambours', '']] = Field(description="Le mode d'ouverture horizontale de la porte, si présent.")
    usage : Optional[Literal['Destinée au passage des piétons', 'Destinée au passage des véhicules', '']] = Field(description="L'usage de la porte, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut de la porte, si présent.")
    mode_d_ouverture : Optional[Literal['Verticale', 'Horizontale', '']] = Field(description="Le mode d'ouverture de la porte, si présent.")
