# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class portes_et_portails_portails_0(BaseModel):
    type_de_control : Optional[Literal['Vérification périodique']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service du portail, si présent.")
    materiau : Optional[Literal['PVC', 'Bois', 'Aluminium', 'Acier', 'Inox', 'Fer', '']] = Field(description="Le matériau du portail, si présent.")
    modele : Optional[str] = Field(description="Le modèle (ou type) du portail, si présent.")
    usage : Optional[Literal['Destiné au passage des piétons', 'Destiné au passage des véhicules', '']] = Field(description="L'usage du portail, si présent.")
    mode_d_ouverture : Optional[Literal['Horizontale', 'Verticale', '']] = Field(description="Le mode d'ouverture du portail, si présent.")
    mode_de_fonctionnement : Optional[Literal['Manuel', 'Automatique', 'Semi-automatique', '']] = Field(description="Le mode de fonctionnement du portail, si présent.")


class portes_et_portails_portails_1(BaseModel):
    fabricant : Optional[str] = Field(description="La marque du fabricant du portail, si présent.")
    marquage_ce : Optional[bool] = Field(description="Le marquage CE est-il présent.")
    en_location : Optional[bool] = Field(description=".")
    mode_ouverture_verticale : Optional[Literal['Sectionnel', 'Coulissant', 'Levant', '']] = Field(description="Le mode d'ouverture verticale du portail, si présent.")
    mode_ouverture_horizontale : Optional[Literal['Coulissant', 'Sectionnel', 'Battant', '']] = Field(description="Le mode d'ouverture horizontale du portail, si présent.")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut du portail, si présent.")
