# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class rayonnages_rayonnage_metallique_0(BaseModel):
    type_de_control : Optional[Literal['Vérification périodique']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service du rayonnage métallique, si présent.")
    date_de_fabrication : Optional[str] = Field(description="La date de fabrication (peut être appelé plaque) du rayonnage métallique, si présent.")
    mobilite : Optional[Literal['Fixe', 'Mobile']] = Field(description="La mobilité du rayonnage métallique, si présent.")
    longueur_en_m_var : Optional[float] = Field(description="La longueur du rayonnage métallique, si présent.")
    nombre_de_niveaux : Optional[int] = Field(description="Le nombre de niveaux du rayonnage métallique, si présent.")
    hauteur_en_m_var : Optional[float] = Field(description="La hauteur en m du rayonnage métallique, si présent.")


class rayonnages_rayonnage_metallique_1(BaseModel):
    fabricant : Optional[str] = Field(description="La marque du fabricant du rayonnage métallique, si présent.")
    charge_maximale_d_utilisation_kg_paire_de_lisse_var : Optional[int] = Field(description="La charge maximale d'utilisation en kg par paire de lisse du rayonnage métallique, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut du rayonnage métallique, si présent.")


class rayonnages_rayonnage_metallique_2(BaseModel):
    type_element : Optional[str] = Field(description="Le type d'élément du rayonnage métallique, si présent.")
