# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class reseaux_de_distribution_eau_a_consommation_humaine_0(BaseModel):
    type_de_control : Optional[Literal['Prélèvement et analyse de la qualité de l’eau']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_service : Optional[str] = Field(description="La date de mise en service du réseau de distribution d'eau à consommation humaine, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut du reseau de distribution d'eau à consommation humaine, si présent.")
    application_des_eaux : Optional[Literal['Eaux destinées à la boisson (cuisson ou préparation d’aliment)', 'Eaux utilisées pour la fabrication, la transformation, la conservation (ou la commercialisation) de produits', 'Autre', '']] = Field(description="L'application des eaux du réseau de distribution d'eau à consommation humaine, si présent.")
    autre_application_des_eaux : Optional[str] = Field(description=".")
    point_de_prelevements_ou_de_prise_d_echantillons : Optional[Literal['Robinet', 'Source d’eau', 'Autre', '']] = Field(description="Le point de prélèvements ou de prise d'échantillons du réseau de distribution d'eau à consommation humaine, si présent.")
    autre_point_de_prelevement : Optional[str] = Field(description=".")
    denomination_du_point : Optional[str] = Field(description="La dénomination du point de prélèvement ou de prise d'échantillons, si présent.")
