# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class reseaux_de_distribution_eau_chaude_sanitaire_0(BaseModel):
    type_de_control : Optional[Literal['Analyse de légionelle']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service du réseau de distribution d'eau chaude sanitaire, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut du reseau de distribution d'eau chaude sanitaire, si présent.")
    point_de_surveillance : Optional[Literal['Fond de ballon de production et de stockage d’eau chaude sanitaire', 'Point d’usage à risque', 'Retour de boucle', 'Autre', '']] = Field(description="Le point de surveillance du réseau de distribution d'eau chaude sanitaire, si présent.")
    autre_point_de_surveillance : Optional[str] = Field(description=".")
    autre_type_de_point_d_usage_a_risque : Optional[str] = Field(description=".")
    type_de_bain : Optional[Literal['A remous', 'A jet', 'Autre', '']] = Field(description="Le type de bain du réseau de distribution d'eau chaude sanitaire, si présent.")
    autre_type_de_bain : Optional[str] = Field(description=".")
    type_de_point_d_usage_a_risque : Optional[Literal['Douche', 'Douchette', 'Robinet', 'Mélangeur ou mitigeur', 'Bain', 'Autre', '']] = Field(description="Le type de point d'usage à risque du réseau de distribution d'eau chaude sanitaire, si présent.")
