# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class reseaux_de_distribution_rejet_aqueux_0(BaseModel):
    type_de_control : Optional[Literal['Contrôle de la qualité des rejets aqueux']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    categorie_de_rejet_aqueux : Optional[Literal['Eaux usées industrielles', 'Eaux usées domestiques', 'Eaux usées de ruissellement urbaines', 'Eaux usées de ruissellement agricole', 'Autre', '']] = Field(description="La catégorie de rejet aqueux, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service du réseau de distribution de rejet aqueux, si présent.")
    autre_categorie_de_rejet_aqueux : Optional[str] = Field(description=".")
    point_de_prelevements_ou_de_prise_d_echantillons : Optional[str] = Field(description="Le point de prélèvements ou de prise d'échantillons du réseau de distribution de rejet aqueux, si présent.")
    denomination_du_point : Optional[str] = Field(description="La dénomination du point de prélèvement ou de prise d'échantillons, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut du réseau de distribution de rejet aqueux, si présent.")
    type_d_installation_de_rejet_aqueux : Optional[Literal['Station d’épuration (STEP)', 'Réseaux d’égouts', 'Installations industrielles', 'Installations agricoles', 'Traitement des déchets', 'Installations d’extraction', 'Station de traitement', 'Autre', '']] = Field(description="Le type d'installation de rejet aqueux, si présent.")
    autre_type_d_installation : Optional[str] = Field(description=".")
