# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class securite_incendie_dispositif_de_desenfumage_0(BaseModel):
    type_de_control : Optional[Literal['Inspection visuelle', 'Vérification']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service du dispositif de désenfumage, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant du dispositif de désenfumage, si présent.")
    modele : Optional[str] = Field(description="Le modèle (ou type) du dispositif de désenfumage, si présent.")
    quantite_d_ouvrant_present_dans_l_installation : Optional[int] = Field(description="La quantité d'ouvrant présent dans l'installation, si présent.")
    quantite_d_exutoire_present_dans_l_installation : Optional[int] = Field(description="La quantité d'exutoire présent dans l'installation, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut du dispositif de désenfumage, si présent.")


class securite_incendie_dispositif_de_desenfumage_1(BaseModel):
    type_element : Optional[Literal['Extraction naturelle', 'Extraction mécanique', '']] = Field(description="Le type d'élément du dispositif de désenfumage, si présent.")
    type_de_suivi : Optional[Literal['Individuel', 'Ensemble', '']] = Field(description="Le type de suivi du dispositif de désenfumage, si présent.")
