# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class securite_incendie_robinet_incendie_arme_ria_var_0(BaseModel):
    type_de_control : Optional[Literal['Maintenance quinquennale', 'Maintenance décennale', 'Surveillance', 'Vérification']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service du robinet d'incendie armé, si présent.")
    diametre_nominal_du_tuyau_dn_var : Optional[int] = Field(description="Le diamètre nominal du tuyau DN du robinet d'incendie armé, si présent.")
    pression_maximale_de_service_en_bar_var : Optional[float] = Field(description="La pression maximale de service en bar du robinet d'incendie armé, si présent.")
    longueur_en_m_var : Optional[float] = Field(description="La longueur en mètre du robinet d'incendie armé, si présent.")
    raccordement_du_ria : Optional[str] = Field(description="Le raccordement du robinet d'incendie armé, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut du robinet d'incendie armé, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant du robinet d'incendie armé, si présent.")
    classe_s_de_feu_x_couvert_par_l_installation : Optional[Literal['Classe A', 'Classe B', 'Classe C', 'Classe D', 'Classe F', '']] = Field(description="La classe S de feu couvert par l'installation, si présent.")
    presence_d_additif : Optional[bool] = Field(description="La présence d'additif, si présent.")
    stockage_de_l_additif : Optional[Literal['Bidon', 'Cuve', 'Container', 'Fût', 'Autre', '']] = Field(description="Le stockage de l'additif, si présent.")
    reference : Optional[str] = Field(description="La référence du robinet d'incendie armé, si présent.")
    volume_l_var : Optional[float] = Field(description="Le volume en litre du robinet d'incendie armé, si présent.")
    modele : Optional[str] = Field(description="Le modèle (ou type) du robinet d'incendie armé, si présent.")
    nombre_de_ria_dans_l_installation : Optional[int] = Field(description="Le nombre de robinet d'incendie armé dans l'installation, si présent.")
    type_d_additif : Optional[Literal['Émulseur', 'Agent mouillant', 'Agent mouillant moussant', 'Autre', '']] = Field(description="Le type d'additif, si présent.")
    autre_type_d_additif : Optional[str] = Field(description=".")
    type_d_emulseur : Optional[str] = Field(description="Le type d'émulseur, si présent.")
    type_d_agent : Optional[str] = Field(description="Le type d'agent, si présent.")
    autre_type_d_installation : Optional[str] = Field(description=".")
    type_element : Optional[Literal['Fixe', 'Pivotant', 'Sous armoire', 'Poste incendie additivé (PIA)', 'Autre', '']] = Field(description="Le type d'élément du robinet d'incendie armé, si présent.")
    type_de_suivi : Optional[Literal['Individuel', 'Ensemble', '']] = Field(description="Le type de suivi du robinet d'incendie armé, si présent.")
