# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class securite_incendie_installation_de_point_d_eau_incendie_0(BaseModel):
    type_de_control : Optional[Literal['Contrôle périodique']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service de l'installation de point d'eau incendie, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant de l'installation de point d'eau incendie, si présent.")
    caracteristique_pompe_ou_groupe_surpresseur : Optional[str] = Field(description="Les caractéristiques de la pompe ou groupe surpresseur de l'installation de point d'eau incendie, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut de l'installation de point d'eau incendie, si présent.")
    nombre_de_bouche_incendie : Optional[int] = Field(description="Le nombre de bouche incendie de l'installation de point d'eau incendie, si présent.")
    volume_de_la_reserve_incendie_m3_var : Optional[float] = Field(description="Le volume de la réserve incendie en m3 de l'installation de point d'eau incendie, si présent.")
    nombre_de_reserve_incendie : Optional[int] = Field(description="Le nombre de réserve incendie de l'installation de point d'eau incendie, si présent.")
    volume_de_la_citerne_incendie_m3_var : Optional[float] = Field(description="Le volume de la citerne incendie en m3 de l'installation de point d'eau incendie, si présent.")
    nombre_de_citerne_incendie : Optional[int] = Field(description="Le nombre de citerne incendie de l'installation de point d'eau incendie, si présent.")
    sources_d_eau : Optional[str] = Field(description="Les sources d'eau de l'installation de point d'eau incendie, si présent.")
    presence_pompe_ou_groupe_surpresseur : Optional[bool] = Field(description="La présence de pompe ou groupe surpresseur de l'installation de point d'eau incendie, si présent.")
    nombre_de_poteau_incendie : Optional[int] = Field(description="Le nombre de poteau incendie de l'installation de point d'eau incendie, si présent.")
    l_installation_fait_elle_partie_d_un_systeme_en_reseau_var : Optional[bool] = Field(description="L'installation fait-elle partie d'un système en réseau, si présent.")
    reference_commerciale : Optional[str] = Field(description="La référence commerciale de l'installation de point d'eau incendie, si présent.")
    composition_de_l_installation : Optional[Literal['Prise d’incendie', 'Raccord d’alimentation ou réalimentation', 'Détendeur', '']] = Field(description="La composition de l'installation de point d'eau incendie, si présent.")
    nombre_de_detendeur : Optional[int] = Field(description="Le nombre de détendeur de l'installation de point d'eau incendie, si présent.")
    nombre_de_raccord : Optional[int] = Field(description="Le nombre de raccord de l'installation de point d'eau incendie, si présent.")
    nombre_de_prise : Optional[int] = Field(description="Le nombre de prise de l'installation de point d'eau incendie, si présent.")
    nombre_de_point_d_eau_suivi : Optional[int] = Field(description="Le nombre de point d'eau incendie suivi, si présent.")
    decomposition_des_points_d_eau_suivis : Optional[Literal['Bouche incendie', 'Poteau incendie', 'Réserve d’eau', 'Citerne', 'Colonne', 'Canon à eau', '']] = Field(description="La décomposition des points d'eau incendie suivis, si présent.")
    type_de_colonne : Optional[Literal['Sèche', 'En charge', '']] = Field(description="Le type de colonne de l'installation de point d'eau incendie, si présent.")
    type_de_point_d_eau : Optional[Literal['Bouche incendie', 'Poteau incendie', 'Réserve d’eau', 'Citerne', 'Colonne', 'Canon à eau', '']] = Field(description="Le type de point d'eau incendie, si présent.")
    type_de_suivi : Optional[Literal['Individuel', 'Ensemble', '']] = Field(description="Le type de suivi de l'installation de point d'eau incendie, si présent.")
