# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class securite_incendie_porte_coupe_feu_0(BaseModel):
    type_de_control : Optional[Literal['Visite', 'Vérification']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service du dispositif de compartimentage, si présent.")
    en_location : Optional[bool] = Field(description=".")
    reference_commerciale : Optional[str] = Field(description="La référence commerciale du dispositif de compartimentage, si présent.")
    materiau : Optional[str] = Field(description="Le matériau du dispositif de compartimentage, si présent.")
    epaisseur_mm_var : Optional[float] = Field(description="L'épaisseur en mm du dispositif de compartimentage, si présent.")
    modele : Optional[Literal['Porte simple', 'Porte double', '']] = Field(description="Le modèle (ou type) du dispositif de compartimentage, si présent.")
    nombre_de_porte_s_var : Optional[int] = Field(description="Le nombre de portes du dispositif de compartimentage, si présent.")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut de la porte coupe-feu, si présent.")
    temperature_de_declenchement_en_c_var : Optional[str] = Field(description="La température de déclenchement en °C du dispositif de compartimentage, si présent.")
    nombre_de_rideau_x_var : Optional[int] = Field(description="Le nombre de rideaux du dispositif de compartimentage, si présent.")
    classe_de_resistance_au_feu_e_var : Optional[str] = Field(description="La classe de résistance au feu du dispositif de compartimentage, si présent.")
    nombre_de_fermeture_s_var : Optional[str] = Field(description="Le nombre de fermetures du dispositif de compartimentage, si présent.")
    nombre_de_clapet_s_var : Optional[int] = Field(description="Le nombre de clapets du dispositif de compartimentage, si présent.")
    declenchement : Optional[Literal['Automatique', 'Manuel', '']] = Field(description="Le déclenchement du dispositif de compartimentage, si présent.")
    dimension_largeur_x_hauteur_var : Optional[str] = Field(description="Les dimensions largeur x hauteur du dispositif de compartimentage, si présent.")
    nombre_de_dispositif_suivi : Optional[int] = Field(description="Le nombre de dispositif suivi, si présent.")
    autre_type_de_porte : Optional[str] = Field(description=".")
    type_de_rideau : Optional[Literal['Souple', 'Rigide', 'Autre', '']] = Field(description="Le type de rideau du dispositif de compartimentage, si présent.")
    autre_type_de_compartimentage : Optional[str] = Field(description="L'autre type de compartimentage, si présent.")
    autre_type_de_convoyeur : Optional[str] = Field(description=".")
    type_de_convoyeur : Optional[Literal['À rouleaux', ' À chaînes', 'À bandes', ' Autre', '']] = Field(description="Le type de convoyeur du dispositif de compartimentage, si présent.")
    autre_type_de_clapet : Optional[str] = Field(description=".")
    type_de_clapet_coupe_feu : Optional[Literal['Circulaire', 'Rectangulaire', 'Carré', 'Autre', '']] = Field(description="Le type de clapet coupe-feu du dispositif de compartimentage, si présent.")
    type_de_porte : Optional[Literal['Coulissante (à translation horizontale)', "Standard (s'ouvrant dans un seul sens)", 'Battante', 'Basculante', 'Autres', '']] = Field(description="Le type de porte du dispositif de compartimentage, si présent.")
    type_de_dispositif_de_compartimentage : Optional[Literal['Porte coupe-feu', 'Rideau coupe-feu', 'Clapet coupe-feu', 'Fermeture de convoyage', 'Autre', '']] = Field(description="Le type de dispositif de compartimentage, si présent.")
    type_de_fermeture : Optional[Literal['Centralisée', 'Thermique', '']] = Field(description="Le type de fermeture du dispositif de compartimentage, si présent.")
    type_de_suivi : Optional[Literal['Individuel', 'Ensemble', '']] = Field(description="Le type de suivi du dispositif de compartimentage, si présent.")
