# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class securite_incendie_installation_d_extinction_a_gaz_0(BaseModel):
    type_de_control : Optional[Literal['Vérification semestrielle', 'Vérification annuelle', 'Vérification', 'Remise en conformité']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service de l'installation d'extinction à gaz, si présent.")
    nombre_de_reservoirs : Optional[int] = Field(description="Le nombre de réservoirs de l'installation d'extinction à gaz, si présent.")
    appellation_du_gaz_inerte : Optional[str] = Field(description="L'appellation du gaz inerte de l'installation d'extinction à gaz, si présent.")
    agent_extincteur_du_gaz_inhibiteur : Optional[Literal['HFC 227ea', 'HFC 23', 'FC 3-1-10', '']] = Field(description="L'agent extincteur du gaz inhibiteur de l'installation d'extinction à gaz, si présent.")
    appellation_du_gaz_inhibiteur : Optional[str] = Field(description="L'appellation du gaz inhibiteur de l'installation d'extinction à gaz, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant de l'installation d'extinction à gaz, si présent.")
    agent_extincteur_du_gaz_inerte : Optional[Literal['IG 55', 'IG 541', 'IG 01', ' IG 100', '']] = Field(description="L'agent extincteur du gaz inerte de l'installation d'extinction à gaz, si présent.")
    en_location : Optional[bool] = Field(description=".")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut de l'installation d'extinction à gaz, si présent.")
    type_d_installation : Optional[Literal['Modulaire', 'Centralisée', 'Directionnelle', '']] = Field(description="Le type d'installation d'extinction à gaz, si présent.")
    type_de_gaz : Optional[Literal['Gaz inhibiteurs', 'Gaz inertes', '']] = Field(description="Le type de gaz de l'installation d'extinction à gaz, si présent.")
