# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class stockage_corrosif_bassin_0(BaseModel):
    type_de_control : Optional[Literal['Visite périodique']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_d_essai_hydraulique : Optional[str] = Field(description="La date d'essai hydraulique du bassin de stockage corrosif, si présent.")
    date_de_fabrication : Optional[str] = Field(description="La date de fabrication (peut être appelé plaque) du bassin de stockage corrosif, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service du bassin de stockage corrosif, si présent.")
    phrases_de_risque_mentions_de_danger : Optional[Literal['Rien', '']] = Field(description="Les phrases de risque et mentions de danger du produit stocké dans le bassins de stockage corrosif, si présent.")
    adresse_du_fabricant : Optional[str] = Field(description="L'adresse du fabricant du bassin de stockage corrosif, si présent.")
    produit_stocke : Optional[str] = Field(description="Le produit stocké dans le bassin de stockage corrosif, si présent.")
    volume_m3_var : Optional[float] = Field(description="Le volume en mètre cube du bassin de stockage corrosif, si présent.")
    lieu_de_fabrication : Optional[str] = Field(description="Le lieu de fabrication du bassin de stockage corrosif, si présent.")
    materiau : Optional[str] = Field(description="Le matériau du bassin de stockage corrosif, si présent.")
    hauteur_de_la_cuve_m_var : Optional[float] = Field(description="La hauteur de la cuve en mètre du bassin de stockage corrosif, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant du bassin de stockage corrosif, si présent.")
    calorifuge : Optional[str] = Field(description="Le calorifuge du bassin de stockage corrosif, si présent.")
    pression_de_service_bar_var : Optional[float] = Field(description="La pression de service en bar du bassin de stockage corrosif, si présent.")
    le_produit_stocke_est_il_corrosif_var : Optional[bool] = Field(description="Le produit stocké est-il corrosif, si présent.")
    temperature_de_service_c_var : Optional[float] = Field(description="La température de service en °C du bassin de stockage corrosif, si présent.")
    temperature_de_calcul_c_var : Optional[float] = Field(description="La température de calcul en °C du bassin de stockage corrosif, si présent.")
    pression_de_calcul_bar_var : Optional[float] = Field(description="La pression de calcul en bar du bassin de stockage corrosif, si présent.")
    pid : Optional[str] = Field(description="Le PID du bassin de stockage corrosif, si présent.")
    en_location : Optional[bool] = Field(description="Le bassin de stockage corrosif est-il en location, si présent.")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut du bassin de stockage corrosif, si présent.")
    type_de_bassin : Optional[str] = Field(description="Le type de bassin de stockage corrosif, si présent.")
