# Specific element field file
#
# Don't modify this file directly !
# It's generated by features_class_maker.py from values in choices_1.json
#
# To modify the specific element fields:
#  - Modify the choices_1.json file
#  - On mac: cd pipeline, python feature_class_make.py

from typing import Optional, Literal
from pydantic import Field, BaseModel



class stockage_corrosif_reservoir_0(BaseModel):
    type_de_control : Optional[Literal['Visite périodique']] = Field(description="Le type de contrôle effectué sur l'élément, si présent.")
    date_d_essai_hydraulique : Optional[float] = Field(description="La date d'essai hydraulique du réservoir, si présent.")
    date_de_mise_en_service : Optional[str] = Field(description="La date de mise en service du réservoir, si présent.")
    date_de_fabrication : Optional[str] = Field(description="La date de fabrication (peut être appelé plaque) du réservoir, si présent.")
    le_produit_stocke_est_il_corrosif_var : Optional[bool] = Field(description="Le produit stocké est-il corrosif, si présent.")
    produit_stocke : Optional[str] = Field(description="Le produit stocké dans le réservoir, si présent.")
    adresse_du_fabricant : Optional[str] = Field(description="L'adresse du fabricant du réservoir, si présent.")
    lieu_de_fabrication : Optional[str] = Field(description="Le lieu de fabrication du réservoir, si présent.")
    fabricant : Optional[str] = Field(description="La marque du fabricant du réservoir, si présent.")
    calorifuge : Optional[str] = Field(description="Le calorifuge du réservoir, si présent.")
    materiau : Optional[str] = Field(description="Le matériau du réservoir, si présent.")
    pression_de_service_bar_var : Optional[float] = Field(description="La pression de service du réservoir en bar, si présent.")
    phrases_de_risque_mentions_de_danger : Optional[Literal['Rien', '']] = Field(description="Les phrases de risque et mentions de danger du produit stocké dans le réservoir, si présent.")
    temperature_de_service_c_var : Optional[float] = Field(description="La température de service du réservoir en degrés Celsius, si présent.")
    pression_de_calcul_bar_var : Optional[float] = Field(description="La pression de calcul du réservoir en bar, si présent.")
    temperature_de_calcul_c_var : Optional[float] = Field(description="La température de calcul du réservoir en degrés Celsius, si présent.")
    hauteur_du_reservoir_m_var : Optional[float] = Field(description="La hauteur du réservoir en mètres, si présent.")
    pid : Optional[str] = Field(description="Le PID du réservoir, si présent.")
    volume_m3_var : Optional[float] = Field(description="Le volume du réservoir en mètres cube, si présent.")
    en_location : Optional[bool] = Field(description="Le réservoir est-il en location, si présent.")
    status : Optional[Literal['Actif', 'Au chômage', 'Au rebut', 'En stock', 'Au brouillon', '']] = Field(description="Le statut du réservoir, si présent.")
    l_installation_est_elle_soumise_a_declaration_d_dans_la_rubrique_1_6_substances_corrosives_var : Optional[bool] = Field(description="L'installation est-elle soumise à déclaration dans la rubrique 1.6 (substances corrosives), si présent.")
    type_de_reservoir : Optional[str] = Field(description="Le type de réservoir, si présent.")
